### ISSUE TITLE
Player controls & settings panel - distinction

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#48]
Proposed distinction of what functionalities to put under Player controls which once under the settings panel - see balsamiq mockup.

Guiding principle is one of setup things might be under settings, things you might want/need to change more often under main player controls. (+keyboard shortcuts)

![controls](https://user-images.githubusercontent.com/4661975/50004028-acde5380-ff9d-11e8-9cb0-e612cb626363.png)

Initially mentioned under PR https://github.com/bbc/react-transcript-editor/pull/46

## recap of functionalities 
Just a quick re-cap of the separation of functionalities into main control bar, settings panel shortcut tips.

### Main control bar 
- [x] rollback 
- [x] rewind
- [x] fast forward - see [issue #47](https://github.com/bbc/react-transcript-editor/issues/47)
- [X] timecode display 
- [ ] Jump to time functionality - by clicking on timecode - possibly with tool tip to flag option?
- [x] duration display 
- [ ] playback speed indication x1 
- [ ] playback speed control - dropdown to change based on presets (or range with bars?)
- [ ] ~reset playback speed ( Eg on playback speed indication + tooltip?)~ might not be needed if it's a drop down.

###  Settings 
- [ ] roll back customisable amount  
- [ ] pause while typing toggle 
- [ ] scroll sync toggle
- [ ] adjust time-code offset
- [ ] hide timecodes (Toggle?) - https://github.com/bbc/react-transcript-editor/issues/52
- [ ] hide speaker names  (Toggle?)  - https://github.com/bbc/react-transcript-editor/issues/52

### cheat sheets
- [ ] Keyboard shortcut cheat sheet 
- [ ] How does this work - cheat sheet
