### ISSUE TITLE
Optional Speaker info using BBC kaldi diarization/segmentation info

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#80]
**Is your feature request related to a problem? Please describe.**

At the moment speaker labels for BBC kaldi transcript are done on line break. This can add extra work when editing a transcript. Taking into account kaldi speaker diarization info the segmentation and speaker label could be more meaningful.

connected but separate feature from this [project card](https://github.com/bbc/react-transcript-editor/projects/1#card-16154942)

**Describe the solution you'd like**
When choosing BBC Kaldi adding optional Speaker info using BBC kaldi diarization/segmentation info. 
If speaker info is provided in transcript json then use that info to add speaker label and group text.

**Describe alternatives you've considered**
NA

**Additional context**
- speaker and transcript are produced by BBC kaldi as two separate json.
- should be optional in case module is used with transcript from kaldi that does not have speaker labels, and then defaults to punctuation to break paragraphs.

- BBC Kaldi segmentation example

```js
{
	"metadata": {
		"version": "0.0.10"
	},
	"@type": "AudioFile",
	"speakers": [
		{
			"@id": "S0",
			"gender": "M"
		},
		{
			"@id": "S4",
			"gender": "M"
		},
		{
			"@id": "S7",
			"gender": "M"
		},
		{
			"@id": "S8",
			"gender": "F"
		}
	],
	"segments": [
		{
			"@type": "Segment",
			"start": 0.0,
			"duration": 15.57,
			"bandwidth": "S",
			"speaker": {
				"@id": "S0",
				"gender": "M"
			}
		},
		{
			"@type": "Segment",
			"start": 15.58,
			"duration": 11.73,
			"bandwidth": "S",
			"speaker": {
				"@id": "S0",
				"gender": "M"
			}
		},
		{
			"@type": "Segment",
			"start": 27.98,
			"duration": 8.43,
			"bandwidth": "S",
			"speaker": {
				"@id": "S4",
				"gender": "M"
			}
		},
		{
			"@type": "Segment",
			"start": 37.8,
			"duration": 4.12,
			"bandwidth": "S",
			"speaker": {
				"@id": "S4",
				"gender": "M"
			}
		},
		{
			"@type": "Segment",
			"start": 42.52,
			"duration": 4.2,
			"bandwidth": "S",
			"speaker": {
				"@id": "S7",
				"gender": "M"
			}
		},
		{
			"@type": "Segment",
			"start": 48.24,
			"duration": 11.79,
			"bandwidth": "S",
			"speaker": {
				"@id": "S8",
				"gender": "F"
			}
		}
	]
}
```

- example of interpolating speaker with transcript in php by @bevand10 that can be used as starting point for node module

```php
<?
function _KaldiToHtml($data, $timecode=false)
{
    $td=$data->commaSegments->transcription;
    $sd=$data->commaSegments->segmentation;

    # short out if we're just delivering the text
    if (!$timecode) return $td->punct;

    $spos=0;
    $kconfidence=0;
    $kword=0;
    $h='';
    $word=[];
    $speaker=_getspeaker($sd, $spos);
    $currentspeaker=$speaker->id;

    $h.=_newspeaker($speaker, $timecode);

    for ($i=0; $i<count($td->words); $i++) {

        $word=$td->words[$i];

        #if($i==0)file_put_contents('/tmp/djb1', serialize($word));

        $kword++;

        $kconfidence+=$word->confidence;

        if ($word->start < $speaker->to) {
            $h.=_formatword($word);
        } else {
            $spos++;
            $speaker=_getspeaker($sd, $spos);
            if ($currentspeaker!=$speaker->id) {
                $h.=_newspeaker($speaker, $timecode);
                $currentspeaker=$speaker->id;
            }
            $h.=_formatword($word);
        }
    }

    return array($h, $kword, sprintf("%0.2f", 100*($kconfidence/$kword)));
}

function _getspeaker($segments, $spos)
{
    $seg=$segments->segments[$spos];
    return (object)array(
        "from"=>$seg->start,
        "to"=>$seg->start + $seg->duration,
        "id"=>((array)$seg->speaker)['@id'],
    );
}

function _newspeaker($speaker, $timecode)
{
    $h="\n<p></p><div>";
    if ($timecode) {
        $h.="<a class=oj-tc data-from="
        .$speaker->from
        .">"
        .bbc::seconds2timecode($speaker->from)
        ." &nbsp; "
        .str_replace('S', 'Speaker: ', $speaker->id)
        ."</a>";
    }
    return "$h</div>\n";
}

function _formatword($word)
{
    $begin="<span data-st=\"".$word->start."\" data-en=\"".$word->end."\"";

    if ($word->confidence < 0.8)
    {
        return $begin." class=\"oj-lo\">".$word->punct."</span> ";
    }
    else
    {
        return $begin.">".$word->punct."</span> ";
    }
}
?>
```
---

## Todo
- [x]  get speaker diarization segments for Ted Talk Example
- [ ] add optional speaker diarization and keep fallback on punctuation if not present to break paragraphs
- [ ] add logic to interpolate paragraphs with speaker segments
- [ ] test in demo app 

When done
- [ ] update version number
- [ ] publish npm
- [ ] update github pages demo

**Comment by pietrop** [comment]
Found a workaround to convert php to js 😜 using [babel php preset](https://gitlab.com/kornelski/babel-preset-php) here is the result:

```js
function _KaldiToHtml(data, timecode = false) //short out if we're just delivering the text
{
    var td = data.commaSegments.transcription;
    var sd = data.commaSegments.segmentation;
    if (!timecode) return td.punct;
    var spos = 0;
    var kconfidence = 0;
    var kword = 0;
    var h = "";
    var word = Array();

    var speaker = _getspeaker(sd, spos);

    var currentspeaker = speaker.id;
    h += _newspeaker(speaker, timecode);

    for (var i = 0; i < td.words.length; i++) //if($i==0)file_put_contents('/tmp/djb1', serialize($word));
    {
        word = td.words[i];
        kword++;
        kconfidence += word.confidence;

        if (word.start < speaker.to) {
            h += _formatword(word);
        } else {
            spos++;
            speaker = _getspeaker(sd, spos);

            if (currentspeaker != speaker.id) {
                h += _newspeaker(speaker, timecode);
                currentspeaker = speaker.id;
            }

            h += _formatword(word);
        }
    }

    return [h, kword, sprintf("%0.2f", 100 * (kconfidence / kword))];
};

function _getspeaker(segments, spos) {
    var seg = segments.segments[spos];
    return Object({
        from: seg.start,
        to: seg.start + seg.duration,
        id: Array.from(seg.speaker)["@id"]
    });
};

function _newspeaker(speaker, timecode) {
    var h = "\n<p></p><div>";

    if (timecode) {
        h += "<a class=oj-tc data-from=" + speaker.from + ">" + bbc.seconds2timecode(speaker.from) + " &nbsp; " + str_replace("S", "Speaker: ", speaker.id) + "</a>";
    }

    return `${h}</div>\n`;
};

function _formatword(word) {
    var begin = "<span data-st=\"" + word.start + "\" data-en=\"" + word.end + "\"";

    if (word.confidence < 0.8) {
        return begin + " class=\"oj-lo\">" + word.punct + "</span> ";
    } else {
        return begin + ">" + word.punct + "</span> ";
    }
};

```

**Comment by pietrop** [comment]
addressed in PR https://github.com/bbc/react-transcript-editor/pull/93
